### ISSUE TITLE
Why require node >=4.2.2?

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/fsos#2]
Cloud9 seems to use `node v4.1.1` in its workspaces, does that mean I can't use `fsos` or any of its dependents (e.g. `email-login v1.0.0`) in Cloud9?

**Comment by espadrine** [comment]
Potentially. I use ES6 Promises; if you can verify that it works in v4.1.1, we can change it.

**Comment by jankeromnes** [comment]
Actually I think you require https://github.com/then/promise instead of using native promises.

Judging from that module's `.travis.yml`, even `node v0.10` and `v0.12` should be supported.

**Comment by espadrine** [comment]
Picking a version was really a matter of manual verification. If you want, I can spend time when I have some to downgrade my node and find out which versions would work. However, if you tell me that you can run `npm test` with a particular version, I'll trust that it will work in subsequent versions.

**Comment by jankeromnes** [comment]
```
./fsos (master) $ node --version
v4.1.1
./fsos (master) $ npm test

> fsos@1.0.2 test /home/ubuntu/workspace/node_modules/email-login/node_modules/fsos
> node test.js

done
```

Seems to work!

**Comment by jankeromnes** [comment]
Same result on a dependent module:

```
./email-login (master) $ npm test

> email-login@1.0.0 test /home/ubuntu/workspace/node_modules/email-login
> node test/main

done.
```

**Comment by jankeromnes** [comment]
:+1:
